--Q.1
SELECT e.EMPLOYEE_ID, e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME, 
    d.DEPARTMENT_NAME
FROM EMPLOYEES e
INNER JOIN DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;
--Q.2
SELECT d.DEPARTMENT_NAME, COUNT(e.EMPLOYEE_ID)
FROM DEPARTMENTS d
INNER JOIN EMPLOYEES e
ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

--Q.3
SELECT DISTINCT JOB_TITLE
FROM JOBS;

--Q.4
SELECT EMPLOYEE_ID , FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME , SALARY
FROM EMPLOYEES
WHERE SALARY > 5000;

--Q.5
SELECT d.DEPARTMENT_NAME , l.CITY
FROM DEPARTMENTS d
INNER JOIN LOCATIONS l
ON d.LOCATION_ID = L.LOCATION_ID;

--Q.6
SELECT MIN (HIRE_DATE)
FROM EMPLOYEES;

--Q.7
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME , HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > TO_DATE('01-JAN-2010', 'DD-MON-YYYY');

--Q.8
SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES;

--Q.9
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS;

--Q.10
SELECT e.EMPLOYEE_ID, e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME, j.JOB_TITLE
FROM EMPLOYEES e
INNER JOIN JOBS j
ON e.JOB_ID = j.JOB_ID
WHERE j.JOB_TITLE = 'Sales Representative';